# Generated by Django 5.0.6 on 2025-06-22 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[("studio", "Studio"), ("sse", "SSE")],
                        default="studio",
                        max_length=20,
                        verbose_name="Tipo de Configuração",
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(default=dict, verbose_name="Configuração"),
                ),
                (
                    "environments",
                    models.JSONField(default=dict, verbose_name="Ambientes"),
                ),
                ("tools", models.JSONField(default=list, verbose_name="Ferramentas")),
                (
                    "type",
                    models.CharField(
                        choices=[("official", "Official"), ("community", "Community")],
                        default="official",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servidor MCP",
                "verbose_name_plural": "Servidores MCP",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(max_length=255, verbose_name="Aplicação"),
                ),
                ("user_id", models.CharField(max_length=255, verbose_name="Usuário")),
                ("state", models.JSONField(verbose_name="Estado")),
                ("create_time", models.DateTimeField(verbose_name="Criado em")),
                ("update_time", models.DateTimeField(verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Sessão",
                "verbose_name_plural": "Sessões",
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "config_json",
                    models.JSONField(default=dict, verbose_name="Configuração"),
                ),
                (
                    "environments",
                    models.JSONField(default=dict, verbose_name="Ambientes"),
                ),
            ],
            options={
                "verbose_name": "Ferramenta",
                "verbose_name_plural": "Ferramentas",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("provider", models.CharField(max_length=255, verbose_name="Provedor")),
                (
                    "encrypted_key",
                    models.CharField(
                        max_length=255, verbose_name="Chave Criptografada"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="api.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chave de API",
                "verbose_name_plural": "Chaves de API",
            },
        ),
        migrations.CreateModel(
            name="AgentFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="api.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasta de Agentes",
                "verbose_name_plural": "Pastas de Agentes",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Função"
                    ),
                ),
                (
                    "goal",
                    models.TextField(blank=True, null=True, verbose_name="Objetivo"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("llm", "LLM"),
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel"),
                            ("loop", "Loop"),
                            ("a2a", "A2A"),
                            ("workflow", "Workflow"),
                            ("crew_ai", "CrewAI"),
                            ("task", "Task"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Modelo"
                    ),
                ),
                (
                    "instruction",
                    models.TextField(blank=True, verbose_name="Instruções"),
                ),
                ("config", models.JSONField(default=dict, verbose_name="Configuração")),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="api.agentfolder",
                        verbose_name="Pasta",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="api.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente",
                "verbose_name_plural": "Agentes",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=128, verbose_name="Hash da Senha"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Administrador"),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="E-mail Verificado"
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Token de Verificação",
                    ),
                ),
                (
                    "verification_token_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiração da Verificação"
                    ),
                ),
                (
                    "password_reset_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Token de Redefinição de Senha",
                    ),
                ),
                (
                    "password_reset_expiry",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Expiração da Redefinição de Senha",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="api.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Ação")),
                (
                    "resource_type",
                    models.CharField(max_length=255, verbose_name="Tipo de Recurso"),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID do Recurso",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Detalhes"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Endereço IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="api.user",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoria",
                "verbose_name_plural": "Registros de Auditoria",
            },
        ),
    ]
